kind: pipeline
type: docker
name: go test
steps:
  - name: test
    image: golang
    commands:
      - make test
  - name: build
    image: lnl7/nix
    commands:
      - nix-channel --update
      - nix-shell --run "make test"
      - nix-build
