kind: pipeline
type: docker
name: go test
steps:
  - name: fix
    image: golang
    commands:
      - make fix

  - name: lint
    image: golang
    commands:
      - make lint

  - name: vet
    image: golang
    commands:
      - make vet

  - name: test
    image: golang
    commands:
      - make test
    depends_on:
      - fix

  - name: build
    image: golang
    commands:
      - make build
    depends_on:
      - cleanup
      - vet
      - test
