kind: pipeline
type: docker
name: go test
steps:
  - name: cleanup
    image: golang
    commands:
      - make fix
      - make vet
      - make lint
      - make clean
  - name: test
    image: golang
    commands:
      - make test
  - name: build
    image: lnl7/nix
    commands:
      - nix-channel --update
      - nix-shell --run "make test"
      - nix-build
    depends_on:
      - cleanup
